package uk.ac.brighton.uni.ch629.catshop.database.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {"http://www.jooq.org", "3.4.1"},
        comments = "This class is generated by jOOQ")
public class Product implements Serializable {
    private static final long serialVersionUID = -1322214835;

    private final Integer productNumber, stock;
    private final String description, imageLocation;
    private final Double price;

    public Product(Integer productNumber, String description, String imageLocation, Integer stock, Double price) {
        this.productNumber = productNumber;
        this.description = description;
        this.imageLocation = imageLocation;
        this.stock = stock;
        this.price = price;
    }

    public Integer getProductNumber() {
        return this.productNumber;
    }

    public String getDescription() {
        return this.description;
    }

    public String getImageLocation() {
        return this.imageLocation;
    }

    public Integer getStock() {
        return this.stock;
    }

    public Double getPrice() {
        return this.price;
    }
}
