package uk.ac.brighton.uni.ch629.catshop.database;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import uk.ac.brighton.uni.ch629.catshop.database.tables.Product;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Generated(value = {"http://www.jooq.org", "3.4.1"},
        comments = "This class is generated by jOOQ")
public class CatShop extends SchemaImpl {

    /**
     * The singleton instance of <code>CatShop</code>
     */
    public static final CatShop CAT_SHOP = new CatShop();
    private static final long serialVersionUID = 584684252;

    /**
     * No further instances allowed
     */
    private CatShop() {
        super("catshop");
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(Product.PRODUCT);
    }
}
