package uk.ac.brighton.uni.ch629.catshop.database;

import uk.ac.brighton.uni.ch629.catshop.database.tables.Product;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 * <p>
 * Convenience access to all tables in catshop
 */
@Generated(value = {"http://www.jooq.org", "3.4.1"},
        comments = "This class is generated by jOOQ")
public class Tables {

    /**
     * The table catshop.product
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
